/*
* generated by Xtext
*/
package at.bestsolution.persistence.emap;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EMapStandaloneSetup extends EMapStandaloneSetupGenerated{

	public static void doSetup() {
		new EMapStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

