/*
 * generated by Xtext
 */
package at.bestsolution.persistence.emap;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EMapRuntimeModule extends at.bestsolution.persistence.emap.AbstractEMapRuntimeModule {

}
