CREATE TABLE ATTACHMENT
(
	SID_ATTACHMENT int64 IDENTITY PRIMARY KEY
	, BINARY blob
	, DESCRIPTION varchar(255)
	, MIMETYPE varchar(255)
	, TITLE varchar(255)

);


CREATE TABLE CHANGE_SET
(
	SID_CHANGE_SET int64 IDENTITY PRIMARY KEY
	, COMMENT varchar(255)
	, ID varchar(255)
	,  FK_PERSON int64 NOT NULL
	,  FK_SOURCE_REPOSITORY int64 NOT NULL
	,  FK_TASK int64 NOT NULL

);


CREATE TABLE COMMENT
(
	SID_COMMENT int64 IDENTITY PRIMARY KEY
	, DESCRIPTION varchar(255)
	, TITLE varchar(255)
	,  FK_TASK int64 NOT NULL

);


CREATE TABLE COMMENT_ATTACHMENT
(
	SID_COMMENT_ATTACHMENT int64 PRIMARY KEY
	,  FK_COMMENT int64 NOT NULL

);


CREATE TABLE PERSON
(
	SID_PERSON int64 IDENTITY PRIMARY KEY
	, FIRSTNAME varchar(255)
	, LASTNAME varchar(255)
	,  FK_REPOSITORY int64 NOT NULL

);


CREATE TABLE SOURCE_REPOSITORY
(
	SID_SOURCE_REPOSITORY int64 IDENTITY PRIMARY KEY
	, SOURCEURL varchar(255)
	, TYPE varchar(255)
	, WEBURL varchar(255)
	,  FK_REPOSITORY int64 NOT NULL

);


CREATE TABLE TASK
(
	SID_TASK int64 IDENTITY PRIMARY KEY
	, DESCRIPTION varchar(255)
	, STATE varchar(255)
	, TITLE varchar(255)
	,  FK_ASSIGNEE int64 NOT NULL
	,  FK_PRODUCT_VERSION int64 NOT NULL
	,  FK_REPORTER int64 NOT NULL
	,  FK_REPOSITORY int64 NOT NULL
	,  FK_TARGET_VERSION int64 NOT NULL

);


CREATE TABLE TASK_ATTACHMENT
(
	SID_TASK_ATTACHMENT int64 PRIMARY KEY
	,  FK_TASK int64 NOT NULL

);


CREATE TABLE TASK_REPOSITORY
(
	SID_TASK_REPOSITORY int64 IDENTITY PRIMARY KEY
	, DESCRIPTION varchar(255)
	, NAME varchar(255)

);


CREATE TABLE VERSION
(
	SID_VERSION int64 IDENTITY PRIMARY KEY
	, CODENAME varchar(255)
	, DATE timestamp
	, VALUE varchar(255)
	,  FK_REPOSITORY int64 NOT NULL

);



ALTER TABLE CHANGE_SET
	ADD FOREIGN KEY (FK_PERSON) REFERENCES PERSON (SID_PERSON);


ALTER TABLE CHANGE_SET
	ADD FOREIGN KEY (FK_SOURCE_REPOSITORY) REFERENCES SOURCE_REPOSITORY (SID_SOURCE_REPOSITORY);


ALTER TABLE CHANGE_SET
	ADD FOREIGN KEY (FK_TASK) REFERENCES TASK (SID_TASK);


ALTER TABLE COMMENT
	ADD FOREIGN KEY (FK_TASK) REFERENCES TASK (SID_TASK);


ALTER TABLE COMMENT_ATTACHMENT
	ADD FOREIGN KEY (FK_COMMENT) REFERENCES COMMENT (SID_COMMENT);


ALTER TABLE COMMENT_ATTACHMENT
	ADD FOREIGN KEY(SID_COMMENT_ATTACHMENT) REFERENCES ATTACHMENT (SID_ATTACHMENT);
ALTER TABLE PERSON
	ADD FOREIGN KEY (FK_REPOSITORY) REFERENCES TASK_REPOSITORY (SID_TASK_REPOSITORY);


ALTER TABLE SOURCE_REPOSITORY
	ADD FOREIGN KEY (FK_REPOSITORY) REFERENCES TASK_REPOSITORY (SID_TASK_REPOSITORY);


ALTER TABLE TASK
	ADD FOREIGN KEY (FK_ASSIGNEE) REFERENCES PERSON (SID_PERSON);


ALTER TABLE TASK
	ADD FOREIGN KEY (FK_PRODUCT_VERSION) REFERENCES VERSION (SID_VERSION);


ALTER TABLE TASK
	ADD FOREIGN KEY (FK_REPORTER) REFERENCES PERSON (SID_PERSON);


ALTER TABLE TASK
	ADD FOREIGN KEY (FK_REPOSITORY) REFERENCES TASK_REPOSITORY (SID_TASK_REPOSITORY);


ALTER TABLE TASK
	ADD FOREIGN KEY (FK_TARGET_VERSION) REFERENCES VERSION (SID_VERSION);


ALTER TABLE TASK_ATTACHMENT
	ADD FOREIGN KEY (FK_TASK) REFERENCES TASK (SID_TASK);


ALTER TABLE TASK_ATTACHMENT
	ADD FOREIGN KEY(SID_TASK_ATTACHMENT) REFERENCES ATTACHMENT (SID_ATTACHMENT);
ALTER TABLE VERSION
	ADD FOREIGN KEY (FK_REPOSITORY) REFERENCES TASK_REPOSITORY (SID_TASK_REPOSITORY);


