/**
 *
 * $Id$
 */
package at.bestsolution.emf.navi.tests.model.sample.validation;

import at.bestsolution.emf.navi.tests.model.sample.Department;
import at.bestsolution.emf.navi.tests.model.sample.Person;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link at.bestsolution.emf.navi.tests.model.sample.Group}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GroupValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePersons(EList<Person> value);
	boolean validateDepartment(Department value);
}
