/**
 *
 * $Id$
 */
package at.bestsolution.emf.navi.tests.model.sample.validation;

import at.bestsolution.emf.navi.tests.model.sample.Group;

import java.util.Date;

/**
 * A sample validator interface for {@link at.bestsolution.emf.navi.tests.model.sample.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateLastname(String value);
	boolean validateFirstname(String value);
	boolean validateBirthdate(Date value);
	boolean validateGroup(Group value);
}
