/*
* generated by Xtext
*/
package at.bestsolution.persistence.emap.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.persistence.emap.services.EMapGrammarAccess;

public class EMapParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EMapGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.persistence.emap.parser.antlr.internal.InternalEMapParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.persistence.emap.parser.antlr.internal.InternalEMapParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EMapping";
	}
	
	public EMapGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EMapGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
