CREATE TABLE CONTACT_BOOK (
	CB_ID	IDENTITY
);

CREATE TABLE COUNTRY (
	CO_ID	IDENTITY,
	CO_NAME	VARCHAR(255)
);

CREATE TABLE PERSON (
	P_ID		IDENTITY,
	P_LASTNAME	VARCHAR(255),
	P_FIRSTNAME	VARCHAR(255)
);

CREATE TABLE ADDRESS (
	AD_ID			IDENTITY,
	AD_STREET		VARCHAR(255),
	AD_CITY			VARCHAR(255),
	AD_ZIP			VARCHAR(255),
	AD_FK_COUNTRY	LONG,
	AD_FK_PERSON	LONG,
	FOREIGN KEY ( AD_FK_COUNTRY ) REFERENCES COUNTRY (CO_ID),
	FOREIGN KEY ( AD_FK_PERSON ) REFERENCES PERSON (P_ID) 
);