package test.model.emap.mixedkeys;

import test.model.mixedkeys.Person;
import java.util.Map;

public interface MPersonMapper extends at.bestsolution.persistence.ObjectMapper<test.model.mixedkeys.Person> {
	
	// generated by JavaInterfaceGenerator
	public static interface Key extends at.bestsolution.persistence.Key<Person> {
		public java.lang.String id();
	}
	
	// by KeyGenerator
	final static at.bestsolution.persistence.java.KeyLayout<MPersonMapper.Key> PKLayout = new at.bestsolution.persistence.java.KeyLayout<MPersonMapper.Key>(
		new at.bestsolution.persistence.java.KeyLayout.KeyLayoutEntry("id", "ID", java.lang.String.class)) {
		@Override
		public MPersonMapper.Key create(Map<String, Object> values) {
			return new KeyImpl(values);
		}
	};
	
	
	// by KeyGenerator
	final static class KeyImpl extends at.bestsolution.persistence.java.AMapBasedKey<Person> implements MPersonMapper.Key {
		KeyImpl(Map<String, Object> values) {
			super(Person.class, values);
		}
		
		@Override
		public at.bestsolution.persistence.java.KeyLayout<MPersonMapper.Key> getKeyLayout() {
			// TODO think about me some more!
			return PKLayout;
		}
		
		@Override
		public java.lang.String id() {
			return getValue("id");
		}
		
		
		@Override
		public String toString() {
			return "Key(MPerson, " + super.toString() + ")";
		}
	}
	
	
	/**
	 * Find elements managed Domain-Elements with a query like this:
	 * <pre>
	 * SELECT
	 *   *
	 * FROM
	 *   MPERSON
	 *   WHERE
	 *     ID = #{id}
	 * </pre>
	 * 
	 * @param id
	 * 
	 */
	public test.model.mixedkeys.Person selectById(String id);
	/**
	 * Find elements managed Domain-Elements with a query like this:
	 * <pre>
	 * SELECT
	 *   *
	 * FROM
	 *   MPERSON, MLIKES_PERSON_PLACE
	 *   WHERE
	 *     MPERSON.ID = MLIKES_PERSON_PLACE.FK_PERSON AND MLIKES_PERSON_PLACE.FK_PLACE = #{placeId}
	 * </pre>
	 * 
	 * @param placeId
	 * 
	 */
	public java.util.List<test.model.mixedkeys.Person> selectAllForPlace(long placeId);


		/**
		 * Build dynamic query filters
		 */
		public static final class Expression {
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person, Person> self_obj() {
				return new at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person, Person>("id") {
					@Override
					protected <K extends at.bestsolution.persistence.Key<Person>> K getKey(Person o) {
						// TODO howto create an instance of the key here within the interface -.-
						return null;
					}
				};
			}

			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person, Person> MPerson_self_obj() {
					return self_obj();
			}

			/**
			 * Filter on id
			 */
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person> id() { return new at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person>("id");}
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person> MPerson_id() { return id();}
			/**
			 * Filter on name
			 */
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person> name() { return new at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person>("name");}
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person> MPerson_name() { return name();}
			/**
			 * Join with MAddress
			 */
			public static final test.model.emap.mixedkeys.MAddressMapper.Join<Person> addresses() { return new test.model.emap.mixedkeys.MAddressMapper.Join<Person>("addresses");};
			public static final test.model.emap.mixedkeys.MAddressMapper.Join<Person> MPerson_addresses() { return addresses(); }
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Address> addresses_obj() {
				return new at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Address>("addresses."+addresses().id().getProperty()) {
					//protected long getSid(test.model.mixedkeys.Address value) {
					//	return value.getId();
					//}
					@Override
					protected <K extends at.bestsolution.persistence.Key<test.model.mixedkeys.Address>> K getKey(test.model.mixedkeys.Address o) {
						// TODO howto create an instance of the key here within the interface -.-
						return null;
					}
				};
			}

			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Address> MPerson_addresses_obj() {
				return addresses_obj();
			}
			
			
			/**
			 * Join with MPlace
			 */
			public static final test.model.emap.mixedkeys.MPlaceMapper.Join<Person> likes() { return new test.model.emap.mixedkeys.MPlaceMapper.Join<Person>("likes");};
			public static final test.model.emap.mixedkeys.MPlaceMapper.Join<Person> MPerson_likes() { return likes(); }
			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Place> likes_obj() {
				return new at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Place>("likes."+likes().id().getProperty()) {
					//protected long getSid(test.model.mixedkeys.Place value) {
					//	return value.getId();
					//}
					@Override
					protected <K extends at.bestsolution.persistence.Key<test.model.mixedkeys.Place>> K getKey(test.model.mixedkeys.Place o) {
						// TODO howto create an instance of the key here within the interface -.-
						return null;
					}
				};
			}

			public static final at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Place> MPerson_likes_obj() {
				return likes_obj();
			}
			
			
		}

		/**
		 * Do not create instances of this class but use {@link MPersonMapper#metaData()}
		 */
		public static class MetaData {
			public at.bestsolution.persistence.AttributeMetaData<Person,java.lang.String,at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person>> id() {
				return new at.bestsolution.persistence.AttributeMetaData<>(Person.class,java.lang.String.class,Expression.id(),Order.id());
			}
			public at.bestsolution.persistence.AttributeMetaData<Person,java.lang.String,at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<Person>> name() {
				return new at.bestsolution.persistence.AttributeMetaData<>(Person.class,java.lang.String.class,Expression.name(),Order.name());
			}
			public at.bestsolution.persistence.ReferenceMetaData<Person,test.model.mixedkeys.Address,at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Address>> addresses() {
				return new at.bestsolution.persistence.ReferenceMetaData<>(Person.class,test.model.mixedkeys.Address.class,Expression.addresses_obj());
			}
			public at.bestsolution.persistence.ReferenceMetaData<Person,test.model.mixedkeys.Place,at.bestsolution.persistence.expr.PropertyExpressionFactory.EntityExpressionFactory<Person,test.model.mixedkeys.Place>> likes() {
				return new at.bestsolution.persistence.ReferenceMetaData<>(Person.class,test.model.mixedkeys.Place.class,Expression.likes_obj());
			}
		}

		public MetaData metaData();

		/**
		 * Build dynamic query order by
		 */
		public static final class Order {
			/**
			 * Order by for id
			 */
			public static final at.bestsolution.persistence.order.OrderColumnFactory<Person> id() { return new at.bestsolution.persistence.order.OrderColumnFactory<Person>("id");};
			/**
			 * Order by for name
			 */
			public static final at.bestsolution.persistence.order.OrderColumnFactory<Person> name() { return new at.bestsolution.persistence.order.OrderColumnFactory<Person>("name");};
		}

		/**
		 * Build join expressions
		 */
		public static final class Join<O> {
			private final String path;
			public Join(String path) {
				this.path = path;
			}

			/**
			 * Filter on id
			 */
			public final at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<O> id() { return new at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<O>(path+".id");};
			/**
			 * Filter on name
			 */
			public final at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<O> name() { return new at.bestsolution.persistence.expr.PropertyExpressionFactory.StringExpressionFactory<O>(path+".name");};
			/**
			 * Join with MAddress
			 */
			public final test.model.emap.mixedkeys.MAddressMapper.Join<O> addresses() {return new test.model.emap.mixedkeys.MAddressMapper.Join<O>(path+".addresses");};
			/**
			 * Join with MPlace
			 */
			public final test.model.emap.mixedkeys.MPlaceMapper.Join<O> likes() {return new test.model.emap.mixedkeys.MPlaceMapper.Join<O>(path+".likes");};
		}
		/**
		 * Build a delete query
		 */
		public at.bestsolution.persistence.MappedUpdateQuery<Person> deleteAllMappedQuery();

}
