/*
 * generated by Xtext
 */
package at.bestsolution.persistence.emap.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.bestsolution.persistence.emap.ui.internal.EMapActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EMapExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EMapActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EMapActivator.getInstance().getInjector(EMapActivator.AT_BESTSOLUTION_PERSISTENCE_EMAP_EMAP);
	}
	
}
