/*
 * generated by Xtext
 */
package at.bestsolution.persistence.emap.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EMapUiModule extends at.bestsolution.persistence.emap.ui.AbstractEMapUiModule {
	public EMapUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
