/*
 * generated by Xtext
 */
package at.bestsolution.persistence.emap.ui.contentassist

import at.bestsolution.persistence.emap.ui.contentassist.AbstractEMapProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class EMapProposalProvider extends AbstractEMapProposalProvider {
}
